version: 2.1
jobs:
  build-production:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t dockerhiscis/socket-cis:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            docker push dockerhiscis/socket-cis:$CIRCLE_SHA1
            docker tag dockerhiscis/socket-cis:$CIRCLE_SHA1 dockerhiscis/socket-cis:socket-cis-production-latest
            docker push dockerhiscis/socket-cis:socket-cis-production-latest
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:mFFo96GsvTZ9QibIzSMIA0ESehKw2h4ASkC3T/+munE'
      - run:
          name: Deploy app to server demo
          command: |
            ssh -o StrictHostKeyChecking=no his-admin@167.172.87.79 "cd /home/cis-admin/socket-cis/ && ./deploy.sh"
workflows:
  basic-workflow:
    jobs:
      - build-production:
          filters:
            branches:
              only:
                - production